baseurl = "https://malv.one/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  contentTypeName = "/_index.md"
  themeColor = "green"
  showMenuItems = 0
  fullWidthTheme = false
  centerTheme = true
  showLanguageSelector = true

#  [params.exMenu]
#    name = ">..test"
#    [[params.exMenu.menuItems]]
#      name = ">root/ðŸ¸"
#      link = "frog"
#    [[params.exMenu.menuItems]]
#      name = ">root/ðŸŸ "
#      link = "orange"

[languages]
  [languages.en]
    title = "Giorgio malv.one"
    subtitle = ""
    keywords = ""
    copyright = "ðŸŸ¢âš«ðŸŸ¢âš«"
    menuMore = "Cool stuff"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
  
    [languages.en.params.logo]
      logoText = "Giorgio malv.one"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = ">aboutðŸ”µ"
        url = "/about"
        weight = 99
      [[languages.en.menu.main]]
        identifier = "graphics"
        name = ">graphicsðŸŸ£"
        url = "/graphics"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "games"
        name = ">gamesðŸŸ¢"
        url = "/games"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "posts"
        name = ">postsðŸŸ "
        url = "/posts"
        weight = 4
      [[languages.en.menu.main]]
        identifier = "software"
        name = ">softwareðŸ”´"
        url = "/software"
        weight = 5